### ISSUE TITLE
[Architect-fiware-orion-on-aws]

### ISSUE THREAD

**Issue by NguyenDOanNhan** [aws-samples/fiware-orion-on-aws#5]
Hi, thank you for the fiware orion project on aws.

In your diagram, I want to ask why don't you just stop the IOT Agent to manage the device?
Will your devices be sent directly to the Orion Context Broker or will it require programming embedded into the device?

**Comment by jl4nz** [comment]
Hi, you could send directly, but I would recommend to put the entry point behind SSL. You can achieve this by using a certificate in load balancer or adding AWS API gateway. 

You will require to program so client code to interact with Orion, the API is here https://fiware-orion.readthedocs.io/en/master/user/walkthrough_apiv2.html
